### ISSUE TITLE
BACF_bcg

### ISSUE THREAD

**Issue by fengyang95** [lifeng9472/Removing_cosine_window_from_CF_trackers#1]
Nice job! Will you release the BACF_bcg code?

**Comment by soldatjiang** [comment]
@wwdguu [https://github.com/soldatjiang/CF_with_ADMM](https://github.com/soldatjiang/CF_with_ADMM)
I attempt to implement BACF_bcg, and it can successfully track objects, but it severely suffers from distractors in some sequences. I will soon test it on OTB dataset.

**Comment by fengyang95** [comment]
Thank you so much for sharing your code.

**Comment by soldatjiang** [comment]
It performs worse than BACF on OTB-2015 mainly because of distractors, maybe I ignored something in my implementation.
